name: Deploy code to GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v2'

    - name: 'Authenticate with GCP'
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'prj-b-cicd-wif-gh-9abe'
        workload_identity_provider: 'projects/115378629654/locations/global/workloadIdentityPools/foundation-pool/providers/foundation-gh-provider'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
